### ISSUE TITLE
Please fix issues reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [BenAhrdt/ioBroker.lorawan#36]
Errors:
[E162] js-controller 3.3.22 listed as dependency but 4.0.24 is required as minimum, 5.0.19 is recommended. Please update dependency at io-package.json.

Warnings:
[W184] "common.main" is deprecated and ignored. Please remove from io-package.json. Use "main" at package.json instead.

**Comment by BenAhrdt** [comment]
@mcm1957 i cant find a Common Object in Package.json

**Comment by mcm1957** [comment]
Why do you search for it. Please read text:

Please remove from **io-package**.json

**Comment by BenAhrdt** [comment]
@mcm1957 Sorry. i update the files. is it ok?

**Comment by BenAhrdt** [comment]
i think its done. i will close the issue
